// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Body(props) {
  return JsxRuntime.jsxs("main", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "THIS IS A DUMMY PAGE",
                      className: "main--title"
                    }),
                JsxRuntime.jsxs("ol", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: "Use this template to start building your own pages!"
                            }),
                        JsxRuntime.jsx("li", {
                              children: "Edit as you go!"
                            })
                      ],
                      className: "main--facts"
                    })
              ]
            });
}

var make = Body;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
