// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Body(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "Reasons I'm excited to learn React"
                    }),
                JsxRuntime.jsxs("ol", {
                      children: [
                        JsxRuntime.jsx("li", {
                              children: "It's a popular library, so I'll be able to fit in with the cool kids!"
                            }),
                        JsxRuntime.jsx("li", {
                              children: "I'm more likely to get a job as a developer if I know React"
                            })
                      ]
                    })
              ]
            });
}

var make = Body;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
