// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Footer(props) {
  return JsxRuntime.jsx("footer", {
              children: JsxRuntime.jsx("small", {
                    children: "© 2021 Ziroll development. All rights reserved."
                  })
            });
}

var make = Footer;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
