// Generated by ReScript, PLEASE EDIT WITH CARE

import LogoSvg from "../imgs/logo.svg";
import * as JsxRuntime from "react/jsx-runtime";

var logo = LogoSvg;

function Navbar(props) {
  return JsxRuntime.jsx("header", {
              children: JsxRuntime.jsxs("nav", {
                    children: [
                      JsxRuntime.jsx("img", {
                            className: "App-logo",
                            alt: "logo",
                            src: logo
                          }),
                      JsxRuntime.jsxs("ul", {
                            children: [
                              JsxRuntime.jsx("li", {
                                    children: "Pricing"
                                  }),
                              JsxRuntime.jsx("li", {
                                    children: "About"
                                  }),
                              JsxRuntime.jsx("li", {
                                    children: "Contact"
                                  })
                            ],
                            className: "nav--items"
                          })
                    ],
                    className: "nav"
                  }),
              className: "App-header"
            });
}

var make = Navbar;

export {
  make ,
}
/* logo Not a pure module */
