// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Body from "./components/Body.bs.mjs";
import * as Footer from "./components/Footer.bs.mjs";
import * as Header from "./components/Header.bs.mjs";
import LogoSvg from "./imgs/logo.svg";
import * as JsxRuntime from "react/jsx-runtime";

import './App.css'
;

function App(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Header.make, {}),
                JsxRuntime.jsx(Body.make, {}),
                JsxRuntime.jsx(Footer.make, {})
              ],
              className: "App"
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
