// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.mjs";
import * as React from "react";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import './Main.css'
;

var domElement = document.querySelector("#root");

if (domElement == null) {
  Js_exn.raiseError("No element has ID of #root!");
} else {
  Client.createRoot(domElement).render(JsxRuntime.jsx(React.StrictMode, {
            children: JsxRuntime.jsx(App.make, {})
          }));
}

export {
  
}
/*  Not a pure module */
